dist: xenial
sudo: required
language: rust
services:
- docker
cache:
  cargo: true
  directories:
  - "~/.npm"
notifications:
  email: false

install:
  - cargo --version
  - docker --version
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main"
  - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main"
  - sudo apt-get update
  - sudo apt-get install -y clang-7 --allow-unauthenticated
  - clang-7 --version
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - cargo install wasm-pack --force
  - PATH=$HOME/.cargo/bin:$PATH
  - rustup --version
  - nvm install node
  - node --version
  - npm install

script:
  - npm run build:bpf-c
  - npm run build:bpf-rust
  - npm run test
