dist: xenial
sudo: required
language: rust

services:
- docker

cache:
  directories:
  - "~/.npm"

notifications:
  email: false

branches:
  only:
    - master

install:
  - cargo --version
  - docker --version
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main"
  - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main"
  - sudo apt-get update
  - sudo apt-get install -y clang-7 --allow-unauthenticated
  - clang-7 --version
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - PATH=$HOME/.cargo/bin:$PATH
  - rustup --version
  - nvm install node
  - node --version
  - npm install

script:
  - npm run build:bpf-c
  - npm run clean:bpf-c
  - npm run build:bpf-rust
  - npm run test

before_deploy:
  - git add -f dist/program/messagefeed.so
  - git commit -m dist/program/messagefeed.so

deploy:
  - provider: heroku
    api_key:
      secure: C7feMlvjO8YFZoJr2u+qdqsMOCbFSFuFnDhztqoksL2tNsqAF4uHUG3O589hQUlG0hsn3AKvR1fdIT+3EU2HAUJgkJ20snywBEUCK9kPcePqQJpsOzBpIahhT7PE2iVrG0lbrvGFwQ3ET+5yYwwZb74iZfMm7SlgusNnvumqo9TAdJdNvPTifsv+1f888OCpgJTG06nnhjA4nUTpglDqb5KiQBuATyk18eBoDi4t8BcOckrPMOZQn9noL3JZ1nQTxb/Rhyw7y0kwxFSQ4hOGWOr2i3VqlZ+jqsErFs7hUXuM2TtgEnBTT8ablDqbi4KXbU9VfHLMMEP0aIi4LE+iWSTlGZ/h328BkUO47VI3F91BHRJ4pYHczaH+E5nuVQuxS7W1oJRba6UUqsEG5C8jqegdyaPF2ruMgNIFi8aLHa3KtAQepCj6JRDX3bK7hapu741sqlzMuKXhFFyZipSS+tzXglNjHOPsZPRxJJi9hIqRswlU1TTQk1SZZ/o/9/x+A2PmhXAOYHbaLEeMKz/Hzk6wlMKf+6a4aUkwbmFGnZwuDkW+Ad/1bfx2CXWY9bx5p75qFDgLo7kToW7/PGS1X8lHH+UY6DuHJTmNnT1e5nXkCkz93dYt3IDEyx0dX4Ee57Bedep0RAdzFmyLybpfMlv7Y8IUQ61X7JAn1E30mos=
    app: solana-example-messagefeed
    strategy: git
    on:
      repo: solana-labs/example-messagefeed
